package icons

import (
	"bytes"
	"encoding/base64"
	"image"
	"image/png"
	"log"
)

// base64 icons
const (
	playBtn64  = "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAAAXNSR0IArs4c6QAAAH1JREFUWIXt1cEJgDAQRNFVbMb+i0k55hJPouzOTFBhPogn44OsJsI594OOcU1pSQKqz0wFSCEMQAJRAChIFdDGfVdBUMAZDWEBNGRNADK1uMc9zpAKALeJ1oG3gAXQQ4gCXvsM2bUuKWaA+hUzAMlhhACkx3EFIH2xc+4zdY+YEFbYD6UDAAAAAElFTkSuQmCC"
	pauseBtn64 = "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAAAXNSR0IArs4c6QAAAFNJREFUWIXtljEKwCAQwGL//0x9h10USqc7UHRIQHTIQbhJEJHDlIDTE3MZF4AnEDBpO9xoQPvdq9zUBrZggAEGGGCAARH6OPXzXuECF3xIROQ4L/CnEz9Rryr6AAAAAElFTkSuQmCC"

	forwardBtn64 = "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAAAXNSR0IArs4c6QAAAIJJREFUWIXtlFEOgCAMQ4fxILv/qbwJfpE0iJSJ+GPfF0mXtWMEMyGEEGvJrGAbbNJrxPTpAGg0o08FOMCkZcT0W/ZAbTFxMElEp0RWgEY4cU9fEuBVIisoOJyTXW/BLUAkQG08otO30GpUg01a9T09M4/IG2BhR4b5nMc/pBBC/IcTIU0bzxaPN5QAAAAASUVORK5CYII="
	backBtn64    = "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAAAXNSR0IArs4c6QAAAIBJREFUWIXtlFEKwCAMQ+vYQXb/S2036X50SN2MtfMvDwQhmqZSFCGEEILRleZb4K5KPxzSQwGQ8fCreQPUXV0TesPuKFz4KtzTwwF6xq6OLZEh/AVPgCMvSwJ6GDX7sk5ppx3pDQkdyCb2XG385oH0h9kZQMFHGhtm6VdMCCHkBi3MIn+MzxIoAAAAAElFTkSuQmCC"

	shuffleBtn64 = "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAAAXNSR0IArs4c6QAAAQFJREFUWIXtlrEOgyAQhs9uDD5AH4B06eDUhJj48EZj3By6ND5AH8DB0U7XUORQjkqH8k8GzP0fx3EAkJT0DxJKLtTcKRJDS0Fk5kCRV+8fh6lezfvIZjp340dM0iAUBM3nbsyEkg0AlKa5E4ALoq8aDYWSi83cS0VeLToMZe4quGC5IA431yEoAE481jE0IaKs3ARACKFkEwLAygCeBoQIqXB2J3xcny0AwOV+Lrkx2ACYcjMTUWQ7bnt6xFcBbONcAK8t2Kr2Q7Owp9NxtoJ1uWxB4LdepNRFRgb0NaZAhqnOirzqAeBmg1gNhBrbIHSFPnK4IH3UXmEB+J15UtKWXgFNf+GSDf+zAAAAAElFTkSuQmCC"

	refreshBtn64 = "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAAAXNSR0IArs4c6QAAAJBJREFUWIVjYBgFo2CkA0ZyNPH3av7HJv6x+DpZ5pFkMS7LiZGn2HJaqKWZgRQ7AmYAJQYRo5eJXMOJAR+LrzMScgReB/D3av6ndcrGaTi6yylxCD08QtABA2b50AX0CjYWWhlMlURMjVAgVD/QtCAiJvvhdQAxJRldwIBURpQYSNM2AbUbJEOrSTYKRsGwBAD6N05wJwJqVAAAAABJRU5ErkJggg=="

	searchIcon64 = "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAAAXNSR0IArs4c6QAAAKBJREFUWIXt1d8NQEAMB2CMwTjCIIYwhCEMQozDGjw1uTRO+te99PcmNP2uiV5VRSKFU1M/HPrxTp/3YyPXqgC4MY4W8lmcNm+X9UzfXfPUWSCyhdAcN8YBiBTRSIos86qmnh6imULxCQQg/gKTRQSRTEG9it0BOQg0015SJjcahnAQZgApwhQgQZgDuAgXAAfhBqAiXAFUhHs4yywS+T0P+V5Z6Bu/xaAAAAAASUVORK5CYII="
)

var icons = map[string]string{
	"play":    playBtn64,
	"pause":   pauseBtn64,
	"forward": forwardBtn64,
	"back":    backBtn64,
	"shuffle": shuffleBtn64,
	"refresh": refreshBtn64,
	"search":  searchIcon64,
}

func GetIcon(iconName string) image.Image {
	icon64 := icons[iconName]
	return getIcon(icon64)
}

func getIcon(icon string) image.Image {
	bicons, err := base64.StdEncoding.DecodeString(icon)
	if err != nil {
		log.Fatal(err.Error())
	}
	i, err := png.Decode(bytes.NewReader(bicons))
	if err != nil {
		log.Fatal(err.Error())
	}
	return i
}
